"""Add Aqi table

Revision ID: 121e724bcde6
Revises: 
Create Date: 2025-08-27 12:11:34.876218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121e724bcde6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('index_value', sa.Integer(), nullable=False),
    sa.Column('index_category', sa.String(), nullable=False),
    sa.Column('calculation_date_st', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_index')
    # ### end Alembic commands ###
