"""Update Aqi table string insted datetime

Revision ID: 3a9bc5cadd81
Revises: 9d2f0d515f27
Create Date: 2025-08-27 12:52:56.019517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9bc5cadd81'
down_revision = '9d2f0d515f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_index', schema=None) as batch_op:
        batch_op.alter_column('calculation_date_st',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_index', schema=None) as batch_op:
        batch_op.alter_column('calculation_date_st',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
