"""Update Aqi table added datetime again

Revision ID: 9d2f0d515f27
Revises: de1fa6a0fdb6
Create Date: 2025-08-27 12:52:15.395043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2f0d515f27'
down_revision = 'de1fa6a0fdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_index', schema=None) as batch_op:
        batch_op.alter_column('calculation_date_st',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_index', schema=None) as batch_op:
        batch_op.alter_column('calculation_date_st',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
