"""Update Aqi table strind insted datetime

Revision ID: de1fa6a0fdb6
Revises: 121e724bcde6
Create Date: 2025-08-27 12:35:53.743732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1fa6a0fdb6'
down_revision = '121e724bcde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_index', schema=None) as batch_op:
        batch_op.alter_column('calculation_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('calculation_date_st',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_index', schema=None) as batch_op:
        batch_op.alter_column('calculation_date_st',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('calculation_date',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
